// <auto-generated />
using System;
using DairyApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DairyApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250817131900_AddDiaryEntryTable")]
    partial class AddDiaryEntryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DairyApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "lets go to mountains",
                            Created = new DateTime(2025, 8, 17, 18, 49, 0, 217, DateTimeKind.Local).AddTicks(8564),
                            Title = "went hiking"
                        },
                        new
                        {
                            Id = 2,
                            Content = "went shopping with joe",
                            Created = new DateTime(2025, 8, 17, 18, 49, 0, 217, DateTimeKind.Local).AddTicks(8567),
                            Title = "went shopping"
                        },
                        new
                        {
                            Id = 3,
                            Content = "went playing with joe",
                            Created = new DateTime(2025, 8, 17, 18, 49, 0, 217, DateTimeKind.Local).AddTicks(8569),
                            Title = "went playinh"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
